# Generated by Django 3.1.1 on 2022-03-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authoradmin'),
        ('projects', '0002_auto_20220327_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.authoradmin'),
        ),
    ]
