# Generated by Django 3.1.1 on 2022-04-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20220418_1010'),
        ('projects', '0006_auto_20220418_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
    ]
