# Generated by Django 3.1.1 on 2022-04-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
        migrations.AddField(
            model_name='project',
            name='prezentation',
            field=models.FileField(blank=True, null=True, upload_to='prezentations/'),
        ),
    ]
