# Generated by Django 3.1.1 on 2022-05-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20220423_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='prezentation',
            new_name='presentation',
        ),
    ]
