# Generated by Django 3.1.1 on 2022-05-23 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_questiontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontext',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
        ),
    ]
