# Generated by Django 2.2.8 on 2020-07-18 09:59

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_merge_20200708_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatordata',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='donatordata',
            name='domicile',
        ),
        migrations.RemoveField(
            model_name='donatordata',
            name='passportData',
        ),
        migrations.RemoveField(
            model_name='donatordata',
            name='placeOfBirth',
        ),
        migrations.RemoveField(
            model_name='donatordata',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='donatordata',
            name='website',
        ),
        migrations.AddField(
            model_name='legalentitydonatordata',
            name='TIN',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='TIN'),
        ),
        migrations.AddField(
            model_name='legalentitydonatordata',
            name='headquarters',
            field=django_countries.fields.CountryField(default=None, max_length=30, verbose_name='headquarters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalentitydonatordata',
            name='postAddress',
            field=models.CharField(blank=True, max_length=200, verbose_name='postAdress'),
        ),
        migrations.AlterField(
            model_name='donatordata',
            name='TIN',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='donatordata',
            name='postAddress',
            field=models.CharField(max_length=200, verbose_name='postAdress'),
        ),
        migrations.AlterField(
            model_name='legalentitydonatordata',
            name='EIK',
            field=models.CharField(max_length=50, verbose_name='EIK'),
        ),
        migrations.AlterField(
            model_name='legalentitydonatordata',
            name='website',
            field=models.CharField(blank=True, max_length=100, verbose_name='website'),
        ),
    ]
