# Generated by Django 2.2.8 on 2020-07-17 14:20

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_merge_20200708_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatordata',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='donatordata',
            name='domicile',
        ),
        migrations.RemoveField(
            model_name='donatordata',
            name='passportData',
        ),
        migrations.RemoveField(
            model_name='donatordata',
            name='placeOfBirth',
        ),
        migrations.RemoveField(
            model_name='donatordata',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='donatordata',
            name='website',
        ),
        migrations.AddField(
            model_name='legalentitydonatordata',
            name='TIN',
            field=models.CharField(default=None, max_length=10, verbose_name='TIN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalentitydonatordata',
            name='headquarters',
            field=django_countries.fields.CountryField(default=None, max_length=30, verbose_name='citizenship'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalentitydonatordata',
            name='postAddress',
            field=models.CharField(default=None, max_length=20, verbose_name='postAdress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentitydonatordata',
            name='website',
            field=models.CharField(blank=True, max_length=100, verbose_name='website'),
        ),
    ]
