# Generated by Django 2.2.8 on 2020-07-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20200718_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentitydonatordata',
            name='TIN',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='legalentitydonatordata',
            name='postAddress',
            field=models.CharField(max_length=200, verbose_name='postAdress'),
        ),
    ]
