# Generated by Django 2.2.8 on 2020-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_auto_20200717_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentitydonatordata',
            name='TIN',
            field=models.CharField(default=None, max_length=10, verbose_name='TIN'),
        ),
    ]
