# Generated by Django 2.2.8 on 2020-07-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_auto_20200719_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneysupport',
            name='anonymous',
        ),
        migrations.AddField(
            model_name='moneysupport',
            name='pay_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='donatordata',
            name='TIN',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='moneysupport',
            name='payment_method',
            field=models.CharField(default='Unspecified', max_length=20, verbose_name='Choose a payment method'),
        ),
    ]
