# Generated by Django 2.2.8 on 2020-07-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20200717_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatordata',
            name='TIN',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='legalentitydonatordata',
            name='TIN',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='TIN'),
        ),
    ]
