# Generated by Django 2.2.8 on 2020-07-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20200720_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=None, null=True, verbose_name='birthdate'),
        ),
    ]
