# Generated by Django 2.2.8 on 2020-07-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20200717_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatordata',
            name='TIN',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='legalentitydonatordata',
            name='postAddress',
            field=models.CharField(blank=True, max_length=200, verbose_name='postAdress'),
        ),
    ]
