# Generated by Django 2.2.8 on 2020-07-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20200725_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketqr',
            name='validated_at',
            field=models.DateTimeField(null=True, verbose_name='validated_at'),
        ),
    ]
