# Generated by Django 2.2.8 on 2020-07-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20200717_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentitydonatordata',
            name='TIN',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='TIN'),
        ),
    ]
