# Generated by Django 2.2.8 on 2020-08-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_answer_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('project', 'question', 'user')},
        ),
    ]
