# Generated by Django 3.1.1 on 2022-05-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_auto_20220505_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileanswer',
            name='file_answer',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='longanswer',
            name='long_answer',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='questions',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questions'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='short_answer',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
