# Generated by Django 3.1.1 on 2022-05-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20220505_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='question_type',
            field=models.CharField(choices=[('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('choice_answer', 'Choice Answer'), ('file_answer', 'File Answer')], default='Short Answer', max_length=100),
        ),
    ]
