# Generated by Django 3.1.1 on 2022-05-06 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_questionnaire_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='position',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='questions',
        ),
        migrations.AddField(
            model_name='choice',
            name='position',
            field=models.IntegerField(default=0, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='choice',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire'),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='position',
            field=models.IntegerField(default=0, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire'),
        ),
        migrations.AddField(
            model_name='longanswer',
            name='position',
            field=models.IntegerField(default=0, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='longanswer',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire'),
        ),
        migrations.AddField(
            model_name='shortanswer',
            name='position',
            field=models.IntegerField(default=0, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='shortanswer',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire'),
        ),
    ]
