# Generated by Django 3.1.1 on 2022-05-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_auto_20220506_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
