# Generated by Django 3.1.1 on 2022-05-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_shortanswer_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortanswer',
            name='question_type',
            field=models.CharField(default='Short Answer', max_length=50),
        ),
    ]
