# Generated by Django 3.1.1 on 2022-05-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0008_auto_20220506_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='question_type',
            field=models.CharField(default='Choice Answer', max_length=50),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='question_type',
            field=models.CharField(default='File Answer', max_length=50),
        ),
        migrations.AddField(
            model_name='longanswer',
            name='question_type',
            field=models.CharField(default='Long Answer', max_length=50),
        ),
    ]
