# Generated by Django 3.1.1 on 2022-05-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_auto_20220506_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='position',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='questionnaire',
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='position',
            field=models.IntegerField(default=0, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='question_type',
            field=models.CharField(default='Short Answer', max_length=50),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='short_answer',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
