# Generated by Django 3.1.1 on 2022-05-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0010_auto_20220506_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='longanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionchoice',
            name='short_answer',
        ),
        migrations.RemoveField(
            model_name='shortanswer',
            name='question',
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='question_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='longanswer',
            name='question_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shortanswer',
            name='question_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='question_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='question_type',
            field=models.CharField(default='Choice Answer', max_length=50),
        ),
    ]
