# Generated by Django 3.1.1 on 2022-05-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0011_auto_20220506_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire'),
        ),
    ]
