# Generated by Django 3.1.1 on 2022-05-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0012_questions_questionnaire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
